sonar.projectKey=tiktokliveurl
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests/**,sonar-scan.sh,*.md
sonar.php.coverage.reportPaths=tests/results/clover.xml
sonar.php.tests.reportPath=tests/results/tests.xml